# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

quotes = [
  "He's as useless as a marzipan dildo",
  "I've booked you in for the usual soapy tit wank farewell at No. 10.",
  "Fuck off back to your match reports, ya twat!",
  "How am I supposed to do my job if I don't know WHAT THE FUCK IS GOING ON?! ",
  "It is possible to have a good resignation, you know?!",
  "NOMFuP",
  "Well, you know me, I'm a man of principle. I like to know whether I'm lying to save the skin of a tosser or a moron.",
  "You're worse than dead meat. I don't know what you're laughing at. You're too toxic to even feed to the vultures.",
  "How much fucking shit is there on the menu and WHAT FUCKING FLAVOUR IS IT?!",
  "You're sticking one tit moment on top of another tit moment. That wouldn't happen in real life.",
  "E-mail them FUCKING WADS of information!",
  "Come the fuck in or fuck the fuck off.",
  "I'm a shape-shifter.",
  "Oh, I'm really sorry, you won't hear anymore swearing from us, YOU MASSIVE GAY SHITE! FUCK OFF!",
  "Hey, I'm going to have a swear box installed on Monday.",
  "Did you have a nice Poofmas?",
  "Have you ever travelled like, a hundred miles per hour, head first, through a tunnel full of pig shit?",
  "If he shits I'll give you 500 quid.",
  "I have never seen anyone sweat so much in my entire life. And I've been in a sauna with Pavarotti!",
  "Fuck all, we're not doing nothing because I am not the story here!",
  "How dare you. How dare you! Don't ever, ever call me a bully. I'm so much worse than that.",
  "You were like a sweaty octopus trying to unhook a bra!",
  "There is a glacier of shit at DoSaC! I need you over there with a fucking blowtorch, right now!",
  "Shut it! You're using all the minutes on my \"Talk until you get head cancer\" tariff.",
  "Well half an hour ago you were in with a shot! This is half an hour hence! We've fucking time-travelled, yes?",
  "Tomorrow, from broadsheets to wank rags, I want pages one, two and three to be a profile of Tom looking like a fucking political colossus. Y'know: Tom meeting the Pope, Tom in an NHS hospital chatting to little, baldie kiddies.",
  "And I want page six TO BE FUCKING... ISRAEL OR SOME BULLSHIT, NOT A FUCKING DOSAC, DIPSHIT, LEGACY-DESTRACTING COCK-UP!",
  "Have some fucking chow mein!",
  "I mean the guy is an epic fuck-up. He’s so dense that light bends around him.",
  "I've got more on my plate than a spinster at a wedding. That wasn't a reference to your daughter by the way, Andrew.",
  "Get me Nicola Murray. Yeah, if she says no the only other candidate is my left bollock with a fucking smiley face drawn on it.",
  "A fucking normal chair, right. Not a fucking massive vibrating throne.",
  "What's up with you? You look like you've shat a Lego garage.",
  "Pull in here. See if you can take out that cyclist on the way, I think he's Shadow Cabinet.",
  "AM I GONNA HAVE TO RUN AROUND SLAPPING BADGES ON PEOPLE WITH A BIG TICK ON SOME AND A BIG CROSS ON OTHERS, SO YOU KNOW WHEN TO SHUT YOUR GOB AND WHEN TO OPEN IT?!",
  "You've sent fuckin' Ollie over there to deal with it. FUCKIN' OLLIE! HE'S A FUCKIN', HE'S A FUCKIN' KNITTED SCARF, THAT TWAT! HE'S A FUCKIN' BALACLAVA!",
  "I'm likely to use an awful lot of what we would call \"Violent Sexual Imagery\"",
  "E-fucking-nough.",
  "Today, you have laid your first, big, fat egg of solid fuck.",
  "You took the data loss media strategy and you ate with a lump of E. coli. And then you sprayed it our of your arse at 300mph.",
  "I think we should use the 'carrot and stick' approach. You take a carrot, you stick it up his fucking arse, followed by the stick, followed by an even bigger, rougher carrot.",
  "I had my finger in the dyke but the dyke's very squirty.",
  "Oi, twat-features! I mean that, literally.",
  "When the Opposition are here, you tell them nothing except where the toilets are, but you lie about that.",
  "I will tear your fucking skin off, I will wear it to your mother's birthday party.",
  "I didn't know you were still alive. How's the 80's tribute band?",
  "This is Tom's idea of a joke, and he wonders why we don't let him out in public.",
  "Are you producing porn for the visually impaired?",
  "I'm telling you to fucking stand up you sack of fucking cum, stand the fuck up!",
  "See, you? Get me a fucking Curly Wurly, right?",
  "This is like The Shawshank Redemption, only with more tunneling through shit and no fucking redemption.",
  "There is a huge difference between me saying \"Nicola, I'd like to go for a lovely walk with you\" and \"Nicola, I'm going to make a hat out of your fucking entrails.\"",
  "I went golfing with Stephen Hawking, he's fucking shit. He lied about his handicap.",
  "Sam, prepare my horse. I ride to DoSAC!",
  "Steve, listen, could you eat or fuck whatever's at the door, on your fucking way out please?",
  "I'd rather fuck a real dragon.",
  "Sam, no pissy biscuits.",
  "Quiet Batpeople?",
  "Don’t send Ben to the back-benches, he’ll just wank and eat Pringles.",
  "What the fuck is this? Tinker, Tailor, Soldier, Cunt?",
  "It's not a pony! It's a fucking foal.",
  "Sorry you had to go, but let's face it, you are a fucking waste of skin.",
  "Here he is! The anointed one.",
  "Political fucking mist, no substance, no weight. ",
  "When this inquiry lands, you better have developed a very flat stony face with no expression.",
  "Well, it's just, you know, you keep asking me the same questions, I can't really help it if you don't like the answers.",
  "You don't get to where you are without bending the rules. That's the way it is.",
  "Je ne remember rien.",
  "You know Jackie fucking Chan about me.",
  "I'm as dead as fucking Two-Tone. But I can fashion my own exit.",
  "You ever drive off like that again and I'll stick your meter so far down your throat you'll be able to tell the price of your next shit!"
]

quotes.each do |q|
  Quote.where(text: q).first_or_create
end
